### ISSUE TITLE
Can you please add section to support proxy to reach bitwarden api for onprem server. 

### ISSUE THREAD

**Issue by vinaykadagave** [bitwarden/splunk#6]
Hi Bitwarden Team, 

Could you please add support for proxy configuration in the app.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

Thanks!
